name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-18.04, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.12'
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run vscode:prepublish
    - name: Check
      env:
          DISPLAY: 10
          INSTALL_JUPYTER_EXTENSION: true
      uses: GabrielBB/xvfb-action@v1.4
      with:
        run: |
          npm run lint
          npm test --silent
