name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-20.04, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.12'
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run vscode:prepublish
    - name: Check
      run: npm run lint
    - name: Test Non-Linux
      if: matrix.os != 'ubuntu-20.04'
      run: npm test --silent
    - name: Test Linux
      if: matrix.os == 'ubuntu-20.04'
      run: xvfb-run --auto-servernum npm test --silent
